### ISSUE TITLE
Input limits in form

### ISSUE THREAD

**Issue by YonatanNitzan** [Spikes-2212-Programming-Guild/mercury-web#42]
Stop people from submitting a form with illegal values.

**Comment by itamargreen** [comment]
Part of form validation #22... 

Validation means that 

1. All required fields are filled in
1. the filled in data makes sense (i.e. an alliance can't own a switch for 160 seconds)
1. It doesn't clash with existing data 

The last one is, I think, a bit more important, because it **will** happen. Two scouters might enter information about the same team in the same game because they didn't understand the אחראי סקאוטינג correctly.

Issues can't be merged AFAIK, but you can edit #22 to include things as you go along.

**Comment by YonatanNitzan** [comment]
I agree.

**Comment by YonatanNitzan** [comment]
Included in #22 for the reason mentioned above.
